### PR TITLE
Updated to 2.0.4 (trusty).

### PR DESCRIPTION
**Pull request by SidRoberts**

### CODE REVIEW

**Comment by niden** [comment]
Thank you!

**Comment by sergeyklay** [comment]
:+1:

**Comment by sergeyklay** [comment]
@niden Hm, when this will be in ppa ?

```
$ sudo apt-add-repository ppa:phalcon/stable
$ sudo apt-get update
$ aptitude show php5-phalcon | grep Version
Version: 2.0.1-ppa1~trusty

```

**Comment by sergeyklay** [comment]
@niden [Phalcon 2.0.5 released](https://github.com/phalcon/cphalcon/releases/tag/phalcon-v2.0.5) but in ppa still 2.0.1

**Comment by SidRoberts** [comment]
@sergeyklay 2.0.5 is in the PPA: https://launchpad.net/~phalcon/+archive/ubuntu/stable. :smile:

**Comment by sergeyklay** [comment]
Now, yes

**Pull request merged**
